stages:
    - deploy

Deploy to prod:
    stage: deploy
    script:
        - cp $ENV_PROD .env
        - sudo docker-compose -f docker-compose.yml down
        - sudo docker-compose -f docker-compose.yml up -d --build
    tags:
        - prod
        
