stages:
    - deploy

Deploy to prod:
    stage: deploy
    script:
        - cp $ENV_PROD .env
        #- docker-compose -f docker-compose.yml down
        #- docker-compose -f docker-compose.yml up -d --build
        - docker-compose down
        - docker-compose up -d --build
    tags:
        - prod
        #- deploy
