#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

docker-compose up

python manage.py collectstatic --no-input
python manage.py migrate --no-input

gunicorn config.wsgi:application --bind 0.0.0.0:8000

exec "$@"
