# Generated by Django 4.2.3 on 2023-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='платеж подтвержден'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id намерения платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id метода платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='cтатус платежа'),
        ),
    ]
